#!/usr/bin/env ruby
#
#
require 'find'

HTTP_DIRECTORY='/var/www/html/'
PROJECT = `pwd`.split('/')[-1].strip
DIRECTORY= HTTP_DIRECTORY + PROJECT
CSS_DIRECTORY=HTTP_DIRECTORY + 'css'
IMAGE_DIRECTORY=HTTP_DIRECTORY + 'images'

task :default => [ :css, :images , :parent_install ]
task :parent_install => :deploy 
task :uninstall => :undeploy

task :create_directories do 
   dirs = []
   # Figure out what directories need to be made
   puts "mkdir -p #{DIRECTORY}/images"
   puts "mkdir -p #{DIRECTORY}/css"
   Find.find('.') do | dir|
     dir.each do |file|
       next if file =~ /Rakefile*/
       next if file =~ /^\.\.?$/
       dirs << file.sub!(/^\.\//, '')  if FileTest.directory?(file)
       end
    end
    dirs.each do |dir|
      puts "mkdir -p " + DIRECTORY + "/#{dir}"
      sh "mkdir -p " + DIRECTORY + "/#{dir}"
    end
end


task :deploy => :create_directories do
   filelist = []
   # Find files that are local, and install them  
   Find.find('.') do | dir|
     dir.each do |file|
       next if file =~ /Rakefile*/
       next if file =~ /^\.\.?$/
       next if FileTest.directory?(file)
       # Strip ./ 
       filelist << file.sub!(/^\.\//, '') 
       end
    end
    filelist.each do |file| 
      location =  DIRECTORY + '/' + file
      puts "install -p -m644 #{file} #{location}"
      sh "install -p -m644 #{file} #{location}"
    end
end


task :css do
   puts "mkdir -p #{CSS_DIRECTORY}"
   sh "mkdir -p #{CSS_DIRECTORY}"
   filelist = []
   # Find files that are local, and install them  
   Find.find('../css') do | dir|
     dir.each do |file|
       next if file =~ /Rakefile*/
       next if file =~ /^\.\.?$/
       next if FileTest.directory?(file)
       filelist << file
       end
    end
    filelist.each do |file| 
      location =  DIRECTORY + '/' + file
      puts "install -p -m644 #{file} #{location}"
      sh "install -p -m644 #{file} #{location}"
    end
end

task :images do
   puts "mkdir -p #{IMAGE_DIRECTORY}"
   sh "mkdir -p #{IMAGE_DIRECTORY}"
   filelist = []
   # Find files that are local, and install them  
   Find.find('../images') do | dir|
     dir.each do |file|
       next if file =~ /Rakefile*/
       next if file =~ /^\.\.?$/
       next if FileTest.directory?(file)
       filelist << file
       end
    end
    filelist.each do |file| 
      location =  DIRECTORY + '/' + file
      puts "install -p -m644 #{file} #{location}"
      sh "install -p -m644 #{file} #{location}"
    end
end


desc "Remove everything under #{DIRECTORY}"
task :cleanall do 
  puts "rm -rf #{DIRECTORY}"
  sh "rm -rf #{DIRECTORY}"
end



task :undeploy do 
   dirs = []
   puts "rm -rf #{DIRECTORY}"
   sh "rm -rf #{DIRECTORY}"
end

task :help do
  puts 
  puts "usage #{$0} and a target"
  puts "install 		--> install items into #{DIRECTORY}" 
  puts "uninstall 		--> remove items from #{DIRECTORY}" 
  puts "create_directories 	--> create directories in  #{DIRECTORY}" 
  puts "cleanall	  	--> rm -rf   #{HTTP_DIRECTORY}" 
  puts "help		 	--> display this message" 
end
